services:
  frontend:
    build:
      context: ./vite-project
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "1323:1323"
    networks:
      - app

networks:
  app: